LICENSES_bundled

Fixes #20 
This should comply with the 3-clause BSD license used by pybind11.
@Teschl Can you confirm that if you run `python3 -m build` that `LICENSES_bundled` shows up in the source code archive and wheel that get built?

Add pybind11 license to LICENSES_bundled

---

README.md

Reorganized Readme.md structure. The Linux Guide is mostly the same as before.
1. **For Windows:**
It took quite a while to get Windows to build the package while not crashing during the C/C++ compiling stage. But now that I have got it running, it's pretty straight forward. To make sure that the guide actually works, it would be nice if one of you could follow the steps in the guide, build the package and then just run one of the example files to verify functionality. 
2. **For Mac**
Since I don't own an Apple Laptop, I can't check if the installation works there too. I assume it works the same as on Linux, but I have no way of knowing. I'll add an issue to track this.  (#26 )

Windows Installation Guide

---

examples/test_load_dem.ipynb
src/topotoolbox/__init__.py
src/topotoolbox/grid_object.py
src/topotoolbox/gridmixins/__init__.py
src/topotoolbox/gridmixins/identifyflats.py
src/topotoolbox/gridmixins/magic.py
src/topotoolbox/utils.py

In this pull request, I added the following functions:
- `topotoolbox.load_dem()` enter DEM name as argument, it will download the tif if it isn't already cached.
- `topotoolbox.get_dem_names()` will return a list of all available tifs for `load_dem()`. if we add a .txt which contains all names to the repository which contains the tifs, we can implement it more dynamically. (right now it's just a list in the .py file)
- `topotoolbox.read_tif()` is a wrapper for creating a GridObject. Could be a cleaner way to create a GridObject inspired by pandas (pandas.read_csv creates a pandas.Dataframe).
Since the function `get_save_location()` in `utils.py` is not listed in `__all__` it's not automatically imported when using the package. This way it's "private" and not usable for the user by …

Provide example data

---

docs/api.rst
docs/examples.rst
examples/plotting.ipynb
examples/saving_dem.ipynb
src/topotoolbox/grid_object.py
src/topotoolbox/utils.py

Changelog:
- Add show function to GridObject which plots using matplotlib
- Add show function to utils which is able to plot multiple GridObjects and change the resolution/dpi of the resulting plots
- Add geo-referencing information to GridObject
- Add to_tif function, which can save GridObject as a .tif file
- Add jupyter notebook example for the show functions
- Add new functions to documentation
closes #47 
closes #44 
closes #43

Add show and saving functions

---

.github/workflows/ci.yaml
.gitignore
CMakeLists.txt
pyproject.toml
src/topotoolbox/grid_object.py
src/topotoolbox/utils.py
tests/test_grid_object.py
tests/test_utils.py

In this pull request, I have fixed the problem of row-major/column-major when passing the matrix. Much like in @bgailleton  's solution, I'm using the `order='F'` argument.
```python
grid.z = dataset.read(1).astype(np.float32, order='F')
```
Initially, I experimented with transposing the matrix, but just using `my_matrix.T` does not solve the row-major/column-major problem. I don't think we need to rotate our matrices in order for the functions to work, right?
If not, this fixes #50 .
Other than that, I added a few basic tests and updated the ci.yaml accordingly. 
closes #41 
The oldest supported version is python 3.10 right now. We should figure out if we also want to make it compatible with older versions.

Fix matrix passing to C/C++

---

.github/workflows/ci.yaml

I noticed GitHub Actions was giving us some deprecation warnings. I've moved to actions/checkout@v4 and actions/setup-python@v5, which seem to be the current versions of these actions and which seem to work without changing anything on our end.

Bump versions of actions/checkout and actions/setup-python

---

pyproject.toml

NumPy 2 can build binaries that are compatible with the NumPy 1 C ABI, but not vice versa. As long as we build with NumPy 2, users should be able to use older versions of NumPy without problems.

Fix the build time version of numpy to 2.0.0 or greater

---

CMakeLists.txt
src/lib/grid.cpp
src/topotoolbox/flow_object.py
src/topotoolbox/grid_object.py

Resolves #69.
CMakeLists.txt: Set GIT_TAG to main to access the new boundary conditions API in libtopotoolbox. This should be changed to 2024-W43 before this is merged but after the next weekly release of libtopotoolbox
src/lib/grid.cpp: `wrap_fillsinks` adds a `bc` argument, which it supplies to libtopotoolbox's `fillsinks` directly.
src/topotoolbox/grid_object.py: The boundary conditions are supplied to `GridObject.fillsinks` as an optional argument. If `bc` is not supplied, then the default is to fix the DEM to its value on the exterior and fill all interior pixels that are not NaNs. NaNs are treated as if they were known sinks by temporarily setting the DEM to -infinity and fixing that pixel as if it were a boundary pixel.
If the user passes in their own boundary condition array, we …

Supply boundary conditions to fillsinks and handle NaNs properly

---

pyproject.toml

I changed my mind about specifying versions in pyproject.toml (#68), but I wanted to go ahead and merge that one. I think having requirements.txt for developers and the automated testing infrastructure to have a consistent environment is all right, though we might need to think about how we decide when to bump those versions. We shouldn't constrain users of the library to also have a particular version of the dependencies unless it is necessary for our topotoolbox functionality that a certain dependency version be available.

Remove version specifications from pyproject.toml

---

.github/workflows/release.yml
CMakeLists.txt

This moves towards a solution for #67.
This workflow uses cibuildwheel to build binary wheels of pytopotoolbox on various architectures. When a release is made it will build and test all of these wheels and upload them as assets to the release.
It also sets the CMAKE_POSITION_INDEPENDENT_CODE flag because it seems like we need position independent code in our static libtopotoolbox library to link it successfully on certain platforms.
My plan is to add this workflow, make a release to ensure that everything works as expected, and then add a step to upload to PyPI. I have already implemented and tested that step, but I want to make sure that everything works here before we start uploading.

Add a release workflow

---

.github/workflows/release.yml

This uses twine to upload alongside an API token that is provided as a secret in the testpypi environment.

Add step to upload to test.pypi.org

---

.github/workflows/release.yml

This attempts to use the gh-action-pypi-publish action to publish to PyPI instead of twine. It also uses the Trusted Publishing workflow to publish without an API token.

Switch from test.pypi.org to the main PyPI repository

---

tests/test_flow_object.py
tests/test_grid_object.py

These tests complement the bugfix in #88.
They check after fillsinks is run that the DEM is identical to a saved copy of the original. Since fillsinks is run directly from the _grid module in FlowObject, the FlowObject test is added.

Add tests to ensure DEM is left unchanged by fillsinks

---

src/topotoolbox/stream_object.py
tests/test_stream_object.py

@Teschl: It turns out I was a little confused about what the `StreamObject` arrays needed to look like. This should make everything work properly, but it may not be the best way to do it. Let me know if you see anything that could be improved
--
If there are n pixels within the stream network, as defined by the `stream_pixels` or `threshold` arrays, then `self.stream`, which is equivalent to `STREAMobj.IXgrid` in MATLAB, should be an array of n elements pointing to the linear indices of the pixels within the stream network. This is a node attribute list, because it stores one piece of information per node. I think this was correct in the last iteration.
However, `self.source` (`STREAMobj.ix`) and
`self.target` (`STREAMobj.ixc`) should be arrays of indices into the node attribute lists. …

Number nodes of StreamObject correctly

---

src/topotoolbox/utils.py

Fixes #80
`axes` turns out to be a array with shape `(1, num_grids)`, so we need to index into the first row and the `i`th column when we plot DEM `i`.

utils.show: Index into the multidimensional axes object

---

src/topotoolbox/flow_object.py
src/topotoolbox/grid_object.py
src/topotoolbox/utils.py
tests/test_flow_object.py

See the discussion in #90.
This ensures that these attributes remain synchronized with the underlying Numpy array that stores the data, but should not change the API of the object. It will break code that directly sets these attributes. I believe I have found and corrected all of those in the package.

Make shape, rows and columns properties of GridObject

---

README.md
docs/CONTRIBUTING.md
docs/Makefile
docs/conf.py
docs/index.rst
docs/requirements.txt

The CONTRIBUTING.md was not being picked up because we didn't have `myst_parser` installed in our docs environment. I added `myst_parser` to `docs/conf.py` and `docs/requirements.txt`, and I moved CONTRIBUTING.md to the docs folder for ease of access. The link on the README has also been updated.

Fix links to CONTRIBUTING.md in docs

---

docs/conf.py

I always find it useful to be able to jump directly to the GitHub repository from a documentation page.

Add repository button to the docs

---

docs/index.rst
docs/wrapping.ipynb

This should contain all changes to the documentation originally made in #72 to add a guide for wrapping libtopotoolbox functions.
closes #76

Add wrapping guide to docs

---

src/lib/grid.cpp
src/topotoolbox/flow_object.py
src/topotoolbox/grid_object.py
tests/test_grid_object.py

This adds a `hybrid` option to `GridObject.fillsinks` and `FlowObject` that dispatches to the hybrid morphological reconstruction. My experiments suggest that this is almost always faster than the sequential reconstruction, so `hybrid=True` is the default, which chooses `fillsinks_hybrid`.
Closes #71

Use `fillsinks_hybrid`

---

src/topotoolbox/grid_object.py

This adds the `erode()` function to the `GridObject`. It wraps the `scipy.ndimage.grey_erosion()` function. Like in the Matlab wrapper, all NaNs are set to `inf` before running the erosion and reverted to NaNs afterward. 
The [Matlab](https://de.mathworks.com/help/images/ref/imerode.html#d126e161642) wrapper only supports the argument `SE` (Structuring element) and ignores `nhood`. In the [Python](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.grey_erosion.html) implementation, `footprint` is `nhood` and `structure` is `SE`. I kept both (and `size`) so provide as much customizability as possible to the user.
Right now, the function defaults to size=(3,3) if nothing else is provided. There is no specific reasoning behind that, so if you have a suggestion what the …

Add erode to GridObject

---

src/topotoolbox/grid_object.py

This adds the dilate function to the `GridObject.` Basically the same code as `erode` #105 but using `grey_dilation`. Also `-inf` in place of `inf` when replacing NaNs. Will probably cause merge conflicts after #116 is merged.
closes #104

Add dilate to GridObject

---

src/topotoolbox/flow_object.py
src/topotoolbox/stream_object.py
tests/test_stream_object.py

This series of commits implements the chi transform for `StreamObject`, resolving #75. It uses `streamquad_trapz` from libtopotoolbox to perform the numerical integration. Everything else sets up the data to be integrated.
There is a new `StreamObject.distance` method that returns the interpixel distance for each edge in the stream network. This is not identical to the `STREAMobj.distance` method that computes upstream distance in MATLAB. It is needed to compute the integration weights.
`StreamObject.ezgetnal` extracts node attributes from a `GridObject` or an `ndarray`. It does not do all of the shape and projection validation that `STREAMobj.ezgetnal` does, so be careful not to pass unaligned grids.
This has been tested manually on the perfectworld DEM, where it agrees with MATLAB's …

Implement `StreamObject.chitransform`

---

docs/tutorial/grid.ipynb

Resolves #108
This commit copies the Curvature section from MATLAB's documentation. It implements percentile clipping of the data using Numpy's quantile function and matplotlib's vmin and vmax arguments to imshow.

Add curvature to the Getting Started guide

---

pyproject.toml
src/topotoolbox/grid_object.py

This pull request adds the `evansslope` function to the `GridObject`. There are a few differences to the Matlab implementation:
- removed `removenans` argument, since `scipy.ndimage.convolve` needs NaNs to be removed (so it's always replacing NaNs with nearest neighbor)
- `padval` is renamed `mode`, to better reflect the underlying scipy function.
- Added `partial_derivitives` argument to provide the option to return fx and fy like in Matlab
- removed a bunch of code used for padding the DEM, since the padding is handled in the `convolution` function
I also had to disable the `too-many-lines` pylint error since the file is now larger than 1000 lines.
closes #106

Add Evansslope to GridObject

---

src/topotoolbox/grid_object.py

It seemed simpler to merge #119 and fix the typo here.

Rename partial_derivitives -> partial_derivatives

---

CMakeLists.txt
src/lib/flow.cpp
src/topotoolbox/flow_object.py

This adds a pybind11 wrapper to the _flow module and a method to FlowObject for drainagebasins. Only the full drainagebasins computation is currently supported.
CMakeLists.txt is modified to use an appropriate commit of libtopotoolbox. This can be updated to 2025-W02 or later upon that release.
Resolves #110

Implement drainagebasins

---

src/topotoolbox/grid_object.py

This is useful for plotting drainage basins, and is needed for the Getting Started guide section on `drainagebasins`.

Add shufflelabel method to GridObject

---

docs/tutorial/flow.ipynb

This copies the text from the MATLAB Getting Started guide, but adds an explanation for `shufflelabel` and uses a different color scheme to plot the drainage basins.
The resulting drainage basins look a little weird, but that is because of our known problems routing flow over flat
regions (TopoToolbox/libtopotoolbox#122).

Add Drainage basin delineation section to the Getting Started guide

---

src/topotoolbox/grid_object.py
tests/test_grid_object.py

This represents one way that we might make our interface with libtopotoolbox agnostic to the memory order of our underlying numpy arrays. I have added a property `dims` to `GridObject`, which reverses the order of the dimensions if the array is in row-major layout. `GridObject.shape` still returns `(rows, columns)`. If we pass `self.dims` instead of `self.shape` to the `fillsinks` wrapper, we will now get the same, correct, answer if the `GridObject.z` array is column- or row-major. There is also a test that confirms this behavior.
I did notice some unexpected changes in performance after implementing this. I thought it would tend to speed `fillsinks` up when using row-major data by avoiding the unnecessary copy to column major. However, this was not the case when applying `fillsinks` to …

Make fillsinks memory-order agnostic

---

pyproject.toml

The changes in #125 use opensimplex directly in the tests, and I wanted to be clear that you need opensimplex to run the tests. I left the "opensimplex" optional dependency in there to avoid breaking existing workflows and because it does provide functionality that we use outside of the tests.
I also added pytest to the "test" dependency. I believe this is the only other package we use directly. All of the other test dependencies are transitive dependencies. Cleanly installing everything using `pip install .[test]` in a new virtual environment works, and the tests are able to run successfully.
I did not add version constraints here because I am not sure if there is a minimum version of either pytest or opensimplex we need to run the tests successfully. I remember we some discussion in #68 …

Add test dependencies as an optional dependency

---

docs/tutorial/stream.ipynb
src/topotoolbox/stream_object.py

Resolves #111 
This uses `StreamObject.xy` to construct stream segments and then plots them with a LineCollection from matplotlib.
This API follows the guidelines in
https://matplotlib.org/stable/users/explain/figure/api_interfaces.html#third-party-library-data-object-interfaces
@Teschl: what do you think about doing something like this for the GridObject plotting interface as well? I think this can make our plots a lot easier to compose. A user would plot a StreamObject over a GridObject like
```python
fig, ax = plt.subplots()
dem.plot(ax=ax, cmap="terrain")
S.plot(ax=ax,color='r',linewidth=0.25)
```
The user can then have as much control over the figure and axes as they want. And by forwarding optional keyword arguments, we let users control other parts of the GridObject plot like the …

Plot StreamObjects with line segments (plus an API change for the plotting)

---

src/topotoolbox/grid_object.py

This Pull Request adds the aspect function to the GridObject. It contains the option to use the classify argument, like in Matlab. Some issues still persist with the calculation of values at the edges of a given dem.
closes #109

Add Aspect to GridObject

---

CMakeLists.txt
src/lib/stream.cpp
src/topotoolbox/stream_object.py

This uses libtopotoolbox's new traverse_down_f32_max_add to compute the maximum distance from a channel head for each node in the stream network.
As discussed in #113. The upstream traversal used to identify the stream with the maximum distance is implemented in libtopotoolbox and wrapped but not implemented in Python yet.

Add downstream_distance method to StreamObject

---

CMakeLists.txt
src/lib/flow.cpp
src/lib/grid.cpp
src/topotoolbox/flow_object.py
src/topotoolbox/stream_object.py
tests/test_flow_object.py

This should resolve #146. It required changing `flow_routing_targets` to `flow_routing_d8_edgelist` as expected, but it also required us to switch from using libtopotoolbox's `flow_accumulation` to `flow_accumulation_edgelist`. I had hoped to make this switch otherwise, so this was a good opportunity to do it. There was one other minor libtopotoolbox change to `drainagebasins` that this effort revealed (TopoToolbox/libtopotoolbox#169).
The changes to StreamObject were minimal, updating it to use the new flow accumulation interface and cleaning up some indices in the constructor function. The normal StreamObject functions already use proper edge lists, so once the constructor was fixed, everything worked properly.
The tests did catch a lot of the necessary changes. I added an index check …

Use the new libtopotoolbox flow routing API

---

docs/tutorial/stream.ipynb
src/topotoolbox/stream_object.py

Resolves #114
This was fairly straightforward to implement using the same pattern as normally plotting a StreamObject with a LineCollection. A small modification to `StreamObject.xy` allows a user to pass a tuple of x, and y node attribute lists that are segmented as appropriate. The segmentation is separate from the values of the generated points. If no data are passed it, the previous behavior, which returns the x and y indices of the pixels in the GridObject is preserved.
We use libtopotoolbox's `streamquad_trapz_f32` to compute upstream distance though there are simpler ways to do so with other traversal methods, and we should change that once such traversals are available in libtopotoolbox.
The optional arguments supported by MATLAB's plotdz are not all supported yet. Passing …

Add plotdz to StreamObject

---

docs/tutorial/flow.ipynb

This prevents a visible artifact of smoothing along the boundaries between drainage basins.

docs: Use nearest-neighbor interpolation with discrete data

---

docs/tutorial/stream.ipynb

The new section of docs/tutorial/stream.ipynb, "Modify the stream network", is not yet identical to the MATLAB Getting Started Guide because we still need `klargestconncomps` (#112), but it can now plot the trunk stream in each drainage basin using `StreamObject.trunk` (#153).

Add trunk to the Getting Started Guide

---

CMakeLists.txt
src/lib/stream.cpp
src/topotoolbox/stream_object.py
tests/test_stream_object.py

This version of `klargestconncomps` uses traversals implemented in libtopotoolbox to compute the size of each connected component of the stream network and to propagate the identities of the largest connected components upstream.
test/stream_object.py adds some tests that ensure that `trunk` and `klargestconncomps` create subgraphs of the original stream network. A helper function `issubgraph` could also be included in the `StreamObject` interface, but it is not particularly efficient as it relies on set operations.

Implement klargestconncomps

---

tests/test_stream_object.py

The tall and wide DEMs previously ended up being the same size because the argument order was switched rather than switching the argument values.

Fix numbering of rows and columns in the StreamObject tests

---

tests/test_stream_object.py

This fixes a bunch of pylint warnings for the tests. I am not sure whether we want to turn pylint checks on for the tests, but they can be helpful for consistency.

Clean up the StreamObject tests

---

tests/test_utils.py

@Teschl: these files don't seem to do anything. Is there a reason to keep them around? I gather [from here](https://docs.pytest.org/en/stable/explanation/goodpractices.html) that there are circumstances when you might need an `__init__.py` in the `tests/` directory, but it does not seem like that advice applies to us at the moment.

Remove unused tests/test_utils.py and tests/__init__.py

---

CMakeLists.txt
src/lib/grid.cpp
src/topotoolbox/grid_object.py
tests/test_grid_object.py

Resolves #131 
This adds a wrapper for the libtopotoolbox hillshade function and a method to GridObject that calls that wrapper. The procedure for converting the azimuth angle from a geographic bearing into the grid's coordinate system is rather involved, but it seems to work for our example DEMs. A test is added that compares the hillshades of random DEMs in row- and column-major order to test that this azimuth angle computation is correct. Some comments are added to help explain the process of rotating the azimuth angle.
Note that `GridObject.hillshade` only computes the hillshade, it does not display it. This behaves differently from TopoToolbox v2, but a separate plotting function or a `hillshade` argument to `GridObject.plot` fits more naturally with our existing visualization API.

Add hillshade to GridObject

---

.github/workflows/release.yml

All of the jobs in the release workflow now check that they are running from within the TopoToolbox/pytopotoolbox repository and will not run on forks. Because the job had to be triggered by a release, and because our PyPI trusted publishing setup should only work from the TopoToolbox repository, I think this is not entirely necessary, but I have made the same change to the release workflows in topotoolbox3 and libtopotoolbox.

Only run the release workflow on the main TopoToolbox repository

---

pyproject.toml
src/topotoolbox/grid_object.py

This method computes a hillshade using the recently added `hillshade` method and then blends it with an RGB image represented the colorized data. This manually implements a lot of what matplotlib provides in its colors.LightSource module. However, the most complicated part is computing the hillshade, which we already do through libtopotoolbox. On the other hand, much of the complexity of MATLAB's imageschs function lies in sorting out the colormaps, which we pass off to matplotlib through its usual normalization->colormap pipeline.
The "overlay" and "soft" blend modes are provided by matplotlib, so it seemed reasonable to include them. The "multiply" blend mode is similar to what MATLAB TopoToolbox uses for its hillshading.
I have also included some options to filter the DEM before …

Add a plot_hs method to GridObject

---

src/topotoolbox/stream_object.py

This is to avoid compatibility problems related to the temporary deprecation of `np.bool` from numpy v1.20.0.

Use bool as the data type of the visited array

---

docs/index.rst

If an older version of topotoolbox is installed, this should download and install a newer one.

Add the upgrade flag to the docs

---

.github/workflows/ci.yaml
pyproject.toml

Some tests have suggested that numpy>=1.23.5 will successfully build on all of our platforms with the changes in #169 and #171. This PR fixes that version in pyproject.toml and reruns the tests on CI using this older version.
Closes #172

Fix a minimum supported numpy version

---

src/topotoolbox/stream_object.py
tests/test_stream_object.py

Implements part of #182
s.streampoi("channelheads") or s.streampoi("outlets") will provide a logical node attribute list identifying locations of the channel heads or outlets.
The channelheads initializer tests are converted to use `streampoi`.

Identify outlets and channelheads with streampoi

---

src/topotoolbox/stream_object.py

See #182
The 'bconfluences' is still not supported because it requires an upstream traversal from the confluences.

Identify confluences in `streampoi`

---

src/topotoolbox/flow_object.py
tests/test_flow_object.py

See #189
A new method is added to FlowObject in src/topotoolbox/flow_object.py that computes the indices of a flow path in the downstream direction using the downstream Boolean semiring traversal followed by some index extraction.
A test is added to tests/test_flow_object.py that ensures that the flow path extracted here is identical to the StreamObject constructed using the `channelheads` argument.

Implement `FlowObject.flowpathextract` in the downstream direction

---

src/topotoolbox/grid_object.py
src/topotoolbox/stream_object.py

Resolves #187
This commit adds an `extent` property to `GridObject`, which constructs a bounding box in the order that matplotlib expects for its `extent` argument to `imshow`. This bounding box is then supplied to `imshow` to plot the `GridObject` with the proper coordinates.
`StreamObject.xy` now defaults to using the geotransform to convert the pixel indices into coordinates. `StreamObject.plot` therefore now plots into the coordinate space. The other use of `StreamObject.xy` in `StreamObject.plotdz` uses the `data` argument to `plotdz`, so it is not affected.

Plot GridObjects and StreamObjects with coordinates

---

docs/tutorial/flow.ipynb
docs/tutorial/grid.ipynb
docs/tutorial/stream.ipynb
docs/tutorial/tutorial.ipynb

Resolves #193
The Big Tujunga DEM has been added in TopoToolbox/DEMs#2, so it is now possible to access it using `load_dem`.

Use Big Tujunga DEM in the Getting Started guide

---

src/topotoolbox/grid_object.py

These arguments are required from Numpy 2.0. This should allow us to use np.array and np.asarray to extract data from GridObjects and ndarrays identically. Care must be taken with earlier versions of Numpy, because the semantics of copying have changed.

Pass dtype and copy arguments to GridObject.__array__

---

src/topotoolbox/grid_object.py

This is a small pull request:
- Vectorise the element-wise comparisons and logical operators
- Add a `__repr__` function mimicking the `info` (when the object is called within the interpreter, it helps for debugging in Jupyter lab)
- Add a `duplicate_with_new_data` function to make an easy copy a GridObject with a new z but the same metadata
It passes `pylint` and `mypy`
Let me know if you need other info/changes

Few improvements on GridObject

---

tests/test_grid_object.py

This test randomly generated double-precision DEMs, which were then passed to libtopotoolbox's hillshade as single-precision DEMs. The results were then incorrect, but compared equal to one another. This change forces the DEMs to be single-precision.
However, this change causes the test to fail because the geotransform created for the column-major array is identical to that of the row-major array. A rotation is applied to the column-major geotransform to correct this. `np.allclose` is now used for the comparison because the separate geotransforms lead to small numerical differences between the two hillshades. The length scale of the random DEMs is also increased because unrealistically steep gradients lead to increased numerical differences in the hillshades.

Correct the hillshade order test

---

tests/test_grid_object.py

This is the same change as needed in #205.

Use a single-precision array in the fillsinks test

---

src/topotoolbox/grid_object.py
tests/test_grid_object.py

As [noted](https://github.com/TopoToolbox/pytopotoolbox/pull/204#issuecomment-2760846869), the `excesstopography` memory order test should not have passed.
First we apply the datatype fix previously needed for fillsinks (#206) and hillshade (#205). Then we set the cellsize to make sure that gradients are computed correctly in excesstopography. This corrects the test, but the test now fails.
The following changes make the tests pass
1. Use the newly available (#196) np.asarray functionality for GridObjects to convert the threshold slope and DEM GridObjects.
2. Use np.full_like to construct `threshold_slopes` so that it matches the datatype, shape and order of the DEM. (#201)
3. Remove the datatype and memory layout checks.
4. Pass dims instead of shape (#200)

Fix the row/column major test for excesstopography

---

src/topotoolbox/utils.py

This version now checks whether the coordinate system information exists before accessing it. It should therefore work for plain ndarrays, which can often be supplied in place of GridObjects.

Make `validate_alignment` work for ndarray

---

src/topotoolbox/grid_object.py

Resolves #217 
This uses rasterio functions to transform the bounding box after reprojection.
I also added a default bounding box for when `bounds`is `None`. This lets you plot GridObjects that are not georeferenced.

Transform bounds in GridObject.reproject 

---

src/topotoolbox/grid_object.py

This imitates `numpy.ndarray.astype` so that we can convert the underlying types of `GridObjects` the same way.
This is part of my attempt to get `imposemin` working using only duck-typing of `GridObjects` and `ndarrays` (#194).

Implement `GridObject.astype`

---

src/topotoolbox/flow_object.py
src/topotoolbox/grid_object.py
src/topotoolbox/stream_object.py
tests/test_flow_object.py
tests/test_stream_object.py

This PR changes ezgetnal so that it always returns a copy of the input array. This problem emerged when working on imposemin (https://github.com/TopoToolbox/pytopotoolbox/pull/194) in trying to ensure that we pass views of the appropriate arrays to libtopotoolbox. This does duplicate arrays in some places where it isn't strictly necessary, and we might consider adding a `copy` argument akin to that on `numpy.array` that can suppress these copies.
Since we are copying the array anyway, it is not so hard to make sure that the returned arrays have a given element type especially with #219.
Tests are added to make sure that the copying works as anticipated and that the dtype is changed when requsted.
This also changes the implementation of the `__array__` method on `GridObject` so that it …

Return copies from ezgetnal

---

CMakeLists.txt
docs/api.rst
src/lib/stream.cpp
src/topotoolbox/__init__.py
src/topotoolbox/flow_object.py
src/topotoolbox/stream_functions.py
tests/test_flow_object.py
tests/test_stream_object.py

`imposemin` can take either a `FlowObject` or a `StreamObject`, so it is implemented as a standalone function in the new file src/topotoolbox/stream_functions.py. It uses the (min,+) traversal recently added to libtopotoolbox.
`imposemin` for a `FlowObject` requires the interpixel distances. I have added a method very similar to `StreamObject.distance` that computes these.
Tests are added for both the `StreamObject` and `FlowObject` versions. The tests ensure:
1. `imposemin` does not modify the original DEM. Certain copies are made explicitly in the implementation of `imposemin` to make sure that this is true.
2. The carved DEM is not above the original
3. The gradient is constrained within numerical error by the `minimum_slope` argument.
@Teschl: would you mind taking a look at this? …

Implement imposemin

---

src/topotoolbox/grid_object.py
tests/test_grid_object.py

See #199
As with the other tests, we create a row-major and an identical column-major array, pass both to `identifyflats` and compare the outputs. We also check that the memory layout is preserved by `identifyflats`.
The row-major and column-major arrays already produced identical results in `identifyflats` because the input was converted to column-major before passing it through. This was caught by the second set of tests. By using `self.dims` instead of `self.shape` (#200) and removing the explicit conversion (#201), this test passes.
This also changes the return type of the `raw=True` option. Instead of returning `tuple(output_grid)`, it returns `(output_grid,)`. The former is a tuple of the rows of the output grid, and the latter is a one-element tuple of the 2D output grid, which is …

Add memory ordering test for identifyflats

---

src/topotoolbox/grid_object.py

Numpy v2.2 has introduced some new type checking annotations, and while we don't rely on any of these annotations, mypy unfortunately labels some errors.
Most importantly, there are new shape types, but not all of the numpy operations respect shape types, and these return a default shape type that is incompatible with a more specific type. If you then try to assign this to a variable that has already been assigned, you'll get a type error in mypy.
This affects us because we assign an empty ndarray to GridObject.z when we create a new GridObject from scratch. So calling
```python
output = GridObject()
output.z = np.zeros_like(dem.z)
```
will result in a type error, because the empty array created for output.z has a shape type that is incompatible with the type of np.zeros_like(dem.z).
This …

Type checking changes for Numpy v2.2

---

src/topotoolbox/grid_object.py
tests/test_grid_object.py

See #199
This has a similar structure to other memory order tests. This fails initially because `gradient8` converts its inputs to column major. It is fixed by applying #200 and #201, using the new array interface.

Add memory order test for gradient8

---

tests/test_grid_object.py

See #199
Like with filter, we don't test that curvature preserves the memory order of arrays because scipy.ndimage.convolve always returns row-major arrays.

Add memory order test for curvature

---

CMakeLists.txt
src/lib/grid.cpp
src/topotoolbox/flow_object.py
tests/test_flow_object.py

Due to limitations in libtopotoolbox, flow routing is sensitive to the memory order of the input arrays. TopoToolbox/libtopotoolbox#186 modifies the API for flow_routing_d8_carve and flow_routing_d8_edgelist to take an order parameter (0 => column-major, 1 => row-major). This parameter corrects the search for flow directions so that the flow routing should be identical for identical arrays in either memory order. Our CMakeLists.txt is updated to include this change.
We do not pass the order flag through the Python API, but instead compute it by examining the flags() method on the direction pybind11::array. Note that all of the arrays should have the same memory ordering, but we do not currently enforce that in any way.
A test is added that compares the FlowObject for identical row-major …

Fix memory ordering problems with FlowObject

---

docs/api.rst
src/topotoolbox/utils.py

This adds two new functions to `utils.py`:
- `load_open_topography()`
- `read_from_cache()`
This adds the ability to Load DEM's from OpenTopography by specifying the bounds, global raster dataset and an API-Key. These will be cached to avoid having to download them again if called with the same arguments. There is also the option to save them at a desired path. To make it easier to load already cached datasets, the function `read_from_cache()` can get them from the cache. This way the user can avoid having to input the whole path, if they haven't saved the TIF at a different place using the `save_path` argument.
closes #215

Add automatic downloads from OpenTopography 

---

CMakeLists.txt
src/lib/stream.cpp
src/topotoolbox/stream_object.py
tests/test_stream_object.py

These are a few methods that implement specific versions of `modify` (#140). I am starting to think that exposing these more basic methods is a nicer interface than `modify` with a ton of keyword arguments, especially because those keyword arguments require different types of input. For example, `rmupstreamtoch` takes another `StreamObject` while `streamorder` actually tries to parse an expression.  These three are all based on node attribute lists/GridObjects and a traversal, so they are pretty straightforward.
Tests are added for `upstreamto` and `downstreamto`. The `upstreamto` test makes use of `clean`, but does not actively test it unless the `tall_dem` fixture happens to have some disconnected pixels in its stream network.

Implement `StreamObject.upstreamto`, `StreamObject.downstreamto` and `StreamObject.clean`

---

src/topotoolbox/flow_object.py
tests/test_flow_object.py

See #199
Create DEMs in row- and column-major order, route flow and compute
flow accumulation. These two outputs should be identical.
This test fails with current pytopotoolbox. The flow accumulation rasters are generated in
column-major order, but the source and target indices are either row-
or column-major depending on the source DEM, so the row-major accesses
the incorrect values. This is incorrect, but does not access memory
out of bounds.
A minimal solution to the failed memory order test adds an
`order` attribute to the `FlowObject` and creates the accumulation and
weights rasters with the correct order. The test now passes. I am
unsure if this is a good long-term solution.
Both `FlowObject` and `StreamObject` need to know the
memory order of their underlying grids because they …

Add memory order test for flow_accumulation

---

src/topotoolbox/flow_object.py
tests/test_flow_object.py

See #199
This test requires some fiddly indexing logic to deal with
permutations of the drainage basin labels, which I hope is
well-explained by the comments.
This test fails at first, because the basins array is created with a column-major order. 
Fixing it  is mostly a matter of using `FlowObject.order` to construct the
right kind of output arrays. It also requires a new `FlowObject.dims`
attribute to pass the dimensions in the correct order.

Test the memory order independence of drainagebasins 

---

src/topotoolbox/grid_object.py
tests/test_grid_object.py

Fixes https://github.com/TopoToolbox/pytopotoolbox/issues/247
Older versions of numpy give a 1D array of indices, so result.z was a
flattened version of the grid. Reshaping is cheap because a copy is
not needed, and it works even if the indices are already 2D.

Reshape the output of shufflelabel

---

docs/dev.rst
docs/dev/template.ipynb
docs/dev/wrapping.ipynb
docs/index.rst

This also moves the wrapping notebook into the new `dev` folder so it shows up under Developer Documentation in the sidebar.

Fix some links regarding the new template notebook

---

docs/tutorial/tutorial.ipynb

This makes the other notebooks show up in the table of contents in the left sidebar.
@Teschl: did this tag get stripped by the`nbstripout` pre-commit hook? It looks like it got removed in #208, but I didn't notice it then. I just ran the hook when I made the commit, and it did not remove it, but perhaps you have some lingering local configuration that does strip it?

Tag the Next Steps section with nbsphinx-toctree

---

tests/test_stream_object.py

See #199
This test passes without modifications.

Add a memory order test for StreamObject.distance

---

src/topotoolbox/stream_object.py
tests/test_stream_object.py

See #199
This requires storing the memory order of the `stream` member, derived from the `FlowObject`, and passing that memory order to `np.unravel_index` when indexing with `stream`.

Add memory order test for StreamObject.ezgetnal

---

tests/test_stream_object.py

A user should not directly access the linear indices of a StreamObject because these depend on the memory order. Using `source_indices` and `target_indices` is memory order agnostic.

Refactor issubgraph to use source_ and target_indices

---

tests/test_stream_object.py

See #199
This tests whether StreamObjects, created with arbitrary memory orders, can accept node attribute lists, themselves with arbitrary memory orders, in the `subgraph` function.
This test passes without modification.

Add a memory order test for StreamObject.subgraph

---

tests/test_flow_object.py

This is the same change as #282, but applied to the FlowObject tests.

Factor out the FlowObject isomorphism test

---

src/topotoolbox/grid_object.py

This adds the functions `zscore` and `resize` to the `GridObject`.
Maybe `crop` would be a more fitting name for the `resize` function. Also, having the arguments `left`, `right`, `top` and `bottom` might be unnecessary. The function only needs two x and y values each and figures out which is left/right or top/bottom automatically. Using `highlight_selected` will create a plot which highlights the area the new `GridObject` will be cropped to. 
I am not 100% sure the updating of the bounds and transform is completely correct, so if anything seems off about that please let me know.
Closes #264

Add resize and zscore

---

CMakeLists.txt
src/lib/stream.cpp
src/topotoolbox/stream_object.py
tests/test_stream_object.py

Resolves #305
Resolves #306
This PR implements lowerenv, which computes the lower convex envelope of a stream profile. It relies on the libtopotoolbox function of the same name (TopoToolbox/libtopotoolbox#196).
CMakeLists.txt is updated with the tag of libtopotoolbox that includes lowerenv.
src/lib/stream.cpp wraps lowerenv.
src/topotoolbox/stream_object.py implements lowerenv as a method on StreamObject.
tests/test_stream_object.py adds a property-based test of convexity of the profile. This is the same property-based test used in the libtopotoolbox test suite. It also adds a memory ordering test (#199).

Implement lowerenv

---

src/topotoolbox/stream_object.py

This code and the accompanying note was added before streampoi existed, but since we now have streampoi, it can be removed.

Replace manual outlet computation with streampoi as suggested

---

src/topotoolbox/stream_object.py
tests/test_stream_object.py

This avoids deprecation warnings when testing on older Numpy versions.
numpy.bool as an alias for Python's built-in bool was deprecated in Numpy v1.20 while Numpy's numpy.bool_ type was renamed to numpy.bool in v2.0. All of the options seem to produce identical arrays using the numpy.bool type, and this change helps avoid the deprecation warnings, which make the test logs quite noisy.

Replace uses of np.bool with bool

---

src/topotoolbox/stream_object.py
tests/test_stream_object.py

This should not have been changed in #318, but it was missed because we don't currently have any tests that run this code. This PR also adds a smoke test.

Rename georef -> crs in to_geodataframe

---

docs/tutorial/stream.ipynb

There were two places where equations were not rendering properly.
The first was because of an extra space after the equation.
The second is because of improper escaping. Strings with LaTeX commands need to be raw strings (i.e. r'$\chi$').

Fix rendering of LaTeX in chi maps tutorial

---

docs/tutorial/stream.ipynb
src/topotoolbox/stream_object.py

Resolves #335
This change calls autoscale_view from inside the plot and plotdz methods, so users don't have to call it externally. It adds two keyword arguments, scalex and scaley, that are passed to Axes.autoscale_view() and can be used to control whether the x or y axis is automatically scaled. This could be helpful if you have already plotted a dataset that spans a subset of the stream network and would like to plot the stream network over that dataset without zooming out to the entire stream.
Alternatively, setting the axis limits manually with set_xlim and set_ylim turns autoscaling off for that axis, so later calls to autoscale_view will not automatically scale the axis, regardless of the values of scalex and scaley. If a user has explicitly constrained the axis limits, this change …

Call autoscale_view automatically from StreamObject.{plot, plotdz}

---

src/lib/grid.cpp
src/topotoolbox/grid_object.py
tests/test_grid_object.py

This is the lower-memory version of hillshade available from libtopotoolbox. It can be slightly faster for large DEMs and avoids excessive memory allocation. An option is provided to hillshade to used the fused implementation or not, with the default to use the fused version.
A test is added to ensure that the fused and unfused implementations return the same values.

Use hillshade_fused by default

---

src/topotoolbox/graphflood_object.py
tests/test_graphflood.py

Add unit test for GraphFlood Object alongside a minor fix for ingesting 2D precipitations as numpy array directly.

Add test for graphflood object
