TopoToolbox/pytopotoolbox

LICENSE
=> Add GPL v3.0

src/lib/grid.cpp, src/topotoolbox/grid_object.py, src/topotoolbox/gridmixins/fillsinks.py, src/topotoolbox/gridmixins/info.py, src/topotoolbox/gridmixins/magic.py
Added Docstrings to all python files, enforced max line lengths, and fixed issued pointed out by pylint. Also added comments to `grid.cpp`.
=> Implement Pep8 standard

.github/workflows/ci.yaml, src/topotoolbox/__init__.py, src/topotoolbox/grid_object.py, src/topotoolbox/utils.py
I added another job in the ci.yaml that contains linting and type checking. I used pylint and mypy respectively. Since the `tests/` are still very underdeveloped, I have not added them to the linting tests for now.
We need to decide how we want to handle linting issues. Right now, the result is:
> Your code has been rated at 9.92/10
Which is due to the amount of arguments in some functions. I don't think the pipeline should fail is the score is this close to 10. I'm looking into a solution for this next.
=> Add linting and type checks

src/topotoolbox/grid_object.py
Resolves #82, mostly
`GridObject.reproject` feeds `rasterio.warp.reproject` with the right source information from the provided `GridObject` and with the desired CRS and resolution. This requires that a user pass a `rasterio.crs.CRS` object and possibly a resolution. It does not automatically find the CRS corresponding to the UTM zone of the GridObject or anything, which MATLAB's `reproject2utm` does. We might consider adding a separate method to do so or by dispatching on the crs argument, i.e. `DEM.reproject(crs='utm')` would construct the CRS for the UTM zone of the DEM, but
`DEM.reproject(crs=rasterio.CRS.from_epsg(32613)` would use the provided CRS object.
=> Add reproject method

docs/examples/streamobject.ipynb
This will ensure that it gets run by nbsphinx and the output is generated and rendered.
=> Clear outputs from StreamObject notebook

src/topotoolbox/grid_object.py
Fixes #127
I also took the opportunity to indicate whether the coordinate system is geographic or projected, which will be useful in #73.
=> Report the minimum and maximum data values in GridObject.info

src/topotoolbox/stream_object.py
`StreamObject.xy` returns a list of lists of tuples giving the coordinates of nodes in the stream network that are connected into continuous stream segments. It constructs this list by conducting a depth-first search on the graph, appending nodes to a segment until the stream reaches an outlet or a sink or a previously visited node. The edge list representation does not allow a depth-first search on its own, so an adjacency list is constructed first.
The main difference between `StreamObject.xy` and MATLAB's STREAMobj2XY is that `StreamObject.xy` returns a list of lists of coordinates, while MATLAB returns a pair of NaN-punctuated vectors. The preferred way to plot many lines in matplotlib is with a `LineCollection`, which takes a list of lists of coordinates, which is why this …
=> Add xy method to StreamObject

tests/test_grid_object.py
It seems like the indentation got messed up and this test wasn't run.
=> Make sure the excesstopography TypeError test runs

src/topotoolbox/stream_object.py, tests/test_stream_object.py
=> Implement subgraph

.github/workflows/ci.yaml, src/topotoolbox/grid_object.py
This did not get properly changed after testing on a feature branch.
=> Run CI workflow on main branch

tests/test_grid_object.py
=> Add a test running `excesstopography` with different memory layouts

tests/test_grid_object.py
The fixture creates two identical arrays that differ only in their memory order and in their geotransform, which is needed for hillshade to work correctly.
test_excesstopography_order: Note that we switch from using numpy.array_equal to numpy.allclose because the fixture dems have a different length scale than we were previously using, and there are some slight numerical differences between the two memory orders.
=> Add fixture for the memory order tests

docs/dev.rst
See #232
This continues to be a challenge, but it appears that this should just work if the MSVC Build Tools are installed properly and the CMAKE_GENERATOR variable isn't set to the wrong value.
=> Add some notes for installing under conda on Windows

docs/api.rst, src/topotoolbox/utils.py
This updates the available datasets and changes the function name to load_opentopography as outlined in #239.
closes #239
=> Update load_opentopgraphy function

src/lib/stream.cpp, src/topotoolbox/flow_object.py
Closes https://github.com/TopoToolbox/pytopotoolbox/issues/243
Assigns indices to the outlets and propagates the indices upstream
=> Compute drainage basins from specified outlets 

src/topotoolbox/flow_object.py
If the specified outlets were not outlets of the FlowObject, zeros would be propagated upstream and overwrite the basins. The MATLAB code checks whether the target is zero before overwriting, but we can also use the or-and upstream traversal as shown here. The edge weights are masks with every bit set, and the node attribute list is the drainage basin labels, so this assigned drainage basin labels upstream, but won't overwrite with zeros. Weirder things will happen if you have multiple flow directions: you'll end up with basin labels that are bitwise mixtures of the two downstream labels and thus that might not be a valid basin label. But drainage basins are not defined for divergent flows anyway, so this shouldn't be a problem.
=> drainagebasins: Use the u32 or-and upstream traversal with outlets

pyproject.toml, requirements.txt, src/topotoolbox/stream_object.py
I simply deleted the repo and clone a new one to modify just the needed lines. Here is a new push and it should be better.
One question:
I didn't modify the requirements.txt because I am not sure which version of shapely and geopandas are correct. How can I know this?
Also, shoud I add a short doc?
=> Adding to_shapefile feature, issue with earlier version fixed (?)

tests/test_flow_object.py
This test passes without modification.
=> Add a memory order test for imposemin with a FlowObject

tests/test_stream_object.py
See #199
This test passes without modifications.
=> Add memory order test for downstream distance

tests/test_stream_object.py
The isequivalent test uses the new node_indices, source_indices, and target_indices to create memory-order independent sets of nodes and edges for two StreamObjects. and compares them. This change replaces the idxmap and comparisons in many of the memory order tests. It also finishes hiding the `order` parameter of FlowObject within the tests (see #202).
=> Factor out the StreamObject isomorphism tests

tests/test_stream_object.py
See #199 
This test passes without modifications.
=> Add a memory order test for imposemin with a StreamObject

src/topotoolbox/grid_object.py
=> added colorbar as argument of plot_hs

src/topotoolbox/stream_object.py, tests/test_stream_object.py
added test of gradient in test_stream_object
=> added gradient function to stream_object

src/topotoolbox/flow_object.py, tests/test_flow_object.py
added the respective tests in test_flow_object
=> added dependence_map and influence_map to flow_object

tests/test_stream_object.py
fixed rest of the code with appropiate changes
=> made stream and flow objects fixtures in tests.

.pre-commit-config.yaml, pyproject.toml, requirements.txt
Resolves #320
PRs #326 and #327 replace kvxopt with clarabel.
=> Remove kvxopt from dependencies

CMakeLists.txt, src/lib/graphflood.cpp, src/topotoolbox/__init__.py, src/topotoolbox/graphflood.py, src/topotoolbox/graphflood_object.py, tests/test_graphflood.py
This PR adds a brand new Graphflood Object to manage GraphFlood simulation.
Helps with running the model from scratch, checking convergence, run for longer if needed, ...
It also provides some analysis tools: extract DIscharge in and out (drainage area based vs computed - will be equal if model has converged but can be used for hillslopes that converge very slowly but does not move much in term of flow partitions), flow velocity, discharge per unit width or even river shear stress.
Recent graphflood's PR on libtopotoolbox brought a couple of changes into the API and this PR updates pytopotoolbox to it.
=> Graphflood obj update

src/topotoolbox/graphflood_object.py
Simply fix bug I did not catch with custom boundary conditions
=> GraphFlood patch for boundary conditions

pyproject.toml
Simply bumps the version pre-release
=> Bump to 0.0.7 for release
